### PR TITLE
Added docker support

### PR DESCRIPTION
**Pull request by sarathsp06**
1. Added docker file and docker compose file
2. Updated config.go and main.go logs
3. Docker compose expects environemnt variables to be docker.env file
4. Updated README in favour of docker  file

### CODE REVIEW

**Comment by sarathsp06** [comment]
Addressing #1

**Comment by sarathsp06** [comment]
@himanshub16 could you please review this

**Comment by himanshub16** [comment]
Sorry, it took time. Had to learn bit about using `docker-compose` :stuck_out_tongue: 

Thanks, @sarathsp06 for contributing.

**Comment by sarathsp06** [comment]
Thanks :smile:

**Pull request merged**
